Add files via upload
IamAntonion/cpp-peer-review pull request #1
Opened 2023-11-23 19:49 UTC by IamAntonion

2023-11-23 21:42 UTC, andrey-mikhaylov commented
По-моему в файле ebook.cpp чего-то не хватает...

2023-11-23 21:48 UTC, andrey-mikhaylov commented on ebook.cpp
Неплохо бы наполнить файл каким-нибудь содержимым

2023-11-24 09:30 UTC, andrey-mikhaylov requested changes
надо придумать хорошие имена для переменных
форматирование кода может быть разным, по вкусу, но если оно такое, что код без него читается легче, чем с ним, значит что-то пошло не так.

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +
чем вызвано различие типов users_count_ и pages_to_user_id_?
[cppreference.com](https://en.cppreference.com/w/c/types/size_t): size_t is the unsigned integer type of the result of [sizeof](https://en.cppreference.com/w/c/language/sizeof)
вроде бы смысл size_t тесно связан с объёмом памяти, занимаемой объектами. он по смыслу не равен unsigned int, который в качестве номера страницы вроде бы подходит больше, если уж хочется обратить внимание на положительность значения.
например на каком-то фантастическом 32-битном микроконтроллере size_t мог бы быть 16-битным (памяти мало, больше нет смысла), при этом int 32-битный. так скорее всего не бывает, но не запрещено :)

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +    std::deque<int> users_count_;
переменная с именем users_count_ видимо должна хранить число пользователей, но это контейнер, так что по этой строке вообще не понять, о чём речь, не прочитав остальной код.
видимо надо поработать над придумыванием имён (мне тоже).

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +
форматирование кода должно помогать его читать, но тут проверка на CHEER оторвана от блока, который обрабатывает CHEER, и прилеплена вместо этого к блоку, обрабатывающему READ

в других местах также перевод строки, предшествующий закрывающей скобке блока, визуально разрывает блок, при этом если код, относящийся к следующему блоку, идёт без перевода строки, это только добавляет замешательства.

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +    int people_ = 0;
опять имя, не объясняющее смысл. вроде бы понятно, что это какие-то люди, по типу можно догадаться, что это скорее всего количество, но дальше - только чтение кода может сказать что это.

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +        size_t pages_to_user = pages_to_user_id_[user_id];
имя переменной вводит в заблуждение. по нему непонятно, что это - количество страниц или сам пользователь.
по-моему имя типа "что-то_to_что-тодругое" хорошо подходит к спискам разного рода, сопоставляющим что-то с чем-то другим. или к функциям преобразования типа. но не к результату этого преобразования.

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +    std::deque<size_t> pages_to_user_id_;
имя вводит в заблуждение. по издревле заведённым на этом практикуме традициям наших предков, имя контейнера формата "вася_to_петя" значит, что имея значение "вася" мы можем достать из этого контейнера знечение "петя", а не наоборот.
мне кажется, чтобы имя стало соответствовать смыслу, имя должно быть например
user_id_to_pages_count_
или
pages_for_user_id_

2023-11-24 09:30 UTC, andrey-mikhaylov commented on ebook.cpp
> +void Parce(std::istream& input,
тут видимо очепятка в имени функции

2023-11-24 11:03 UTC, IamAntonion commented on ebook.cpp
> +
вы имеете в виду перенос else if в другую строку? перенос else if в другую строку возможен, но чаще всего встречается такой стиль написания как в 87 строке описан в Google C++ Style Guide (https://google.github.io/styleguide/cppguide.html#Formatting_Looping_Branching)

2023-11-24 18:40 UTC, andrey-mikhaylov commented on ebook.cpp
> +
не совсем. перенос else if в другую строку тоже полезное дело, на мой взгляд, но это уже другая история.

я имею в виду такое, как было в предыдущей версии:
        if (request_type == "READ") {

            тело блока, относящееся к READ
            тело блока, относящееся к READ
            тело блока, относящееся к READ         ________________не хватает пустой строки (не обязательно)
        } else if (request_type == "CHEER"){
                                                                                                    <<< а это лишняя пустая строка
            тело блока, относящееся к CHEER
            тело блока, относящееся к CHEER
            тело блока, относящееся к CHEER
        }

блок READ как бы визуально заканчивается проверкой CHEER

в исправленной версии вы убрали лишние пробелы, и взгляд о них теперь не спотыкается.

2023-11-24 18:55 UTC, IamAntonion commented on ebook.cpp
> +
согласен, выглядит не очень хорошо)

2023-11-24 19:17 UTC, andrey-mikhaylov approved these changes
предыдущие замечания исправлены, но можно немного доработать

2023-11-24 19:17 UTC, andrey-mikhaylov commented on ebook.cpp
> +    } else if (!(number_of_authorized_people - 1)) {
мне кажется, делать логическое отрицание выражения с числами - не очень хорошая практика.
что из этого:
if (!(number_of_authorized_people - 1))
if (number_of_authorized_people-1 == 0)
if (number_of_authorized_people == 1)
читается легче и лучше соответствует смыслу проверки?

2023-11-24 19:17 UTC, andrey-mikhaylov commented on ebook.cpp
> +    }
просто для интереса можно подвергнуть эту функцию рефакторингу в стиле "never nesting", она сразу станет намного лучше читаться

2023-11-24 19:56 UTC, IamAntonion commented on ebook.cpp
> +    }
исправил)

2023-11-24 19:59 UTC, merged