Create domains.cpp
IamAntonion/cpp-peer-review pull request #2
Opened 2023-11-23 19:49 UTC by IamAntonion

2023-11-23 22:07 UTC, andrey-mikhaylov commented on domains.cpp
> +            }
по-моему тут прямо напрашивается
return std::equal(other_domain.domain_title_.begin(), 
                           other_domain.domain_title_.end(), 
                           domain_title_.begin());
вместо 8 строк

2023-11-23 22:07 UTC, andrey-mikhaylov commented on domains.cpp
> +                                                                        });
текст с хаотичными отступами трудно читать

2023-11-23 22:07 UTC, andrey-mikhaylov commented on domains.cpp
> +           return false;
Есть такая концепция - ранний возврат, по-моему у нас про это в курсе было. Позволяет разбить функцию на независимые хорошо различимые части, сначала можно например проверить все ошибки, выйти с признаками ошибок, а потом, в конце функции уже идёт основной код, "позитивный", последними строками в функции заканчиваются последние её действия, ради которых она написана. Тогда и отступ в основном коде уменьшается обычно до единичного, это улучшает читаемость. Функция сокращается и в ширину и в высоту :)

2023-11-23 22:07 UTC, andrey-mikhaylov commented on domains.cpp
> +    // разработайте класс домена
наверное комментарии надо или удалить или откорректировать, они в таком виде помогают писать код, когда его ещё нет, но в готовом коде такие не нужны

2023-11-23 22:07 UTC, andrey-mikhaylov commented on domains.cpp
> +
в задании написано "Разработайте юнит-тесты. Их проверит ваш сокурсник."
наверное надо сделать хоть какие-нибудь

2023-11-23 22:10 UTC, andrey-mikhaylov requested changes
по существу: не хватает юнит-тестов.
неплохо бы сделать рефакторинг для улучшения читаемости.

2023-11-24 08:33 UTC, IamAntonion commented
с ошибками согласен, исправлю

2023-11-24 08:35 UTC, merged

2023-11-24 10:21 UTC, andrey-mikhaylov commented
Вижу, ошибки исправлены, меня всё устраивает.